name: Linting the code in Repository

on:
  pull_request:
    branches: [ tmp/forDebug26 ]
# env:
#   GITHUB_ORG: ${{ github.event.organization }} 

jobs:
  Lintingcode:
    runs-on: linter

    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout repository
        uses: actions/checkout@v2      
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      - name: Dump GitHub context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        
      - name: Super-Linter
        id: linting
        uses: github/super-linter@v4.9.2
        env:      
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      - name: Label on failure
        if: ${{ failure() }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            lintingfailed
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      - name: Comment on failure
        if: ${{ failure() }}
        uses: alawiii521/current-pr-comment@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          comment: "Linting files failed"
      - name: Delete Existing Label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          labels: lintingfailed
      - name: Label on Success
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: LintCheckPassed
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Comment on Success
        uses: alawiii521/current-pr-comment@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          comment: "Lint Check Passed"
