---
name: Run CI checks
on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"
permissions: read-all
jobs:
  TriggerWorkfows:
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}
